---
title: "Complete BugPhyzz Stats"
output:
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{BugPhyzz Stats}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)

```

```{r setup}
library(bugphyzz)
library(magrittr)
library(dplyr)
library(ggplot2)
library(plotly)
```

Load all of the bugphyzz datasets:

```{r load all datasets}
physiologies <- physiologies(keyword = "all") %>% 
  lapply(as_tibble)
```

Source summary statistics functions

```{r}
source(here::here("R/categorical_summary_stats.R"))
source(here::here("R/continuous_summary_stats.R"))
source(here::here("R/taxonomy_functions.R"))
```
```{r}
printGGlist <- function(gglist){
for(gg in gglist){

    print(gg)

}
}
```

NCBI ID Stats

```{r}
ncbi_list <- mapply(function(.x, .y) ncbi_stats(.x, .y), physiologies, names(physiologies), SIMPLIFY = FALSE)
```
```{r warning = FALSE, echo=FALSE, out.width="45%"}
printGGlist(ncbi_list)
```

Categorical attribute stats

# Setup

```{r list of categorical physiologies}
categorical_list <- physiologies[c("antimicrobial resistance", "gram stain",
                                   "habitat", "aerophilicity", "extreme environment",
                                   "shape", "arrangement", "plant pathogenicity",
                                   "animal pathogen", "isolation site",
                                   "antimicrobial sensitivity", "disease association",
                                   "biofilm forming", "growth medium", "spore shape")]
```

```{r fetch ranks for categorical physiologies}
cat_rank <- lapply(categorical_list, fetch_ranks)
```

## Number of genera per attribute of a physiology

```{r}
gen_per_attr <- mapply(function(.x, .y) num_genera_per_attribute(.x, .y), cat_rank, names(cat_rank), SIMPLIFY = FALSE)
```
```{r warning = FALSE, echo=FALSE, out.width="45%"}
printGGlist(gen_per_attr)
```

## Number of taxa without NCBI ID per attribute in physiology dataset

```{r}
taxa_without_attr <- mapply(function(.x, .y) num_taxa_without_ncbi_per_attribute(.x, .y), cat_rank, names(cat_rank), SIMPLIFY = FALSE)
```
```{r warning = FALSE, echo=FALSE, out.width="45%"}
printGGlist(taxa_without_attr)
```



