---
title: "Descriptive statistcs of taxa annotations"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(bugphyzz)
library(dplyr)
library(purrr)
library(ggplot2)
```

```{r, message=FALSE}
phys <- physiologies(keyword = "all")
taxonomy_table <- bugphyzz:::taxonomyAnnotations
## remove prefix
colnames(taxonomy_table) <- sub("bugphyzz_", "", colnames(taxonomy_table)) 
## Select only columns with rank names, not rank ids
taxonomy_table <- select(taxonomy_table, -ends_with("_id", ignore.case = FALSE))
taxonomy_table$NCBI_ID <- as.integer(taxonomy_table$NCBI_ID)
```

```{r}
taxonomy_table %>% 
    count(rank) %>% 
    arrange(-n)
```

# Taxa annotated with NCBI IDs by rank

```{r}
data <- phys %>% 
  map(~ select(.x, all_of(c("NCBI_ID", "Rank")))) %>% 
  map(~ modify_at(.x, "NCBI_ID", as.character)) %>% 
  bind_rows(.id = "dataset") %>% 
  as_tibble()
```

```{r, fig.width=9, fig.height=10}
data %>% 
  mutate(Rank = forcats::fct_relevel(Rank, "genus", "strain", "species")) %>% 
  ggplot(aes(dataset)) +
  geom_bar(aes(fill = Rank), position = "fill") +
  scale_y_continuous(label = scales::percent) +
  labs(x = "Dataset", y = "NCBI_ID",
       title = "Taxa Annotations with NCBI IDs in Bugphyzz",
       subtitle = "physiologies + fattyAcidComposition") +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "bottom", plot.margin = unit(c(1,2,1,1),"cm"))
```

## Session information

```{r}
sessionInfo()
```


